CREATE TABLE users
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    SORARE_ID  VARCHAR(36) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP          NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP          NULL
);