CREATE TABLE sorare_tokens
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID    INT       NOT NULL,
    TOKEN      TEXT      NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NULL     DEFAULT NOW(),

    CONSTRAINT FK_SORARE_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES users (ID)
);