CREATE TABLE refresh_tokens
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID    INT          NOT NULL,
    TOKEN      VARCHAR(255) NOT NULL,
    EXPIRES_AT TIMESTAMP    NOT NULL,
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT FK_REFRESH_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES users (ID),
    CONSTRAINT UQ_REFRESH_TOKEN_TOKEN UNIQUE (TOKEN)
);