# Access token configuration
sogaffer.jwt.access.aud=SoGaffer
sogaffer.jwt.access.secret=dGVzdHNlY3JldGtleWZvcnRlc3RpbmdwdXJwb3NlcyE=
sogaffer.jwt.access.duration=3600
sogaffer.encryption.secret=dGVzdGVuY3J5cHRpb25rZXlmb3J0ZXN0cHVycG9zZXM=

sogaffer.cookie.secure=false

# Database connection configuration
spring.datasource.url=jdbc:h2:mem:sogaffer_test;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop


# Flyway configuration
spring.flyway.enabled=false